### ISSUE TITLE
webassembly build is not working for Safari 12.1

### ISSUE THREAD

**Issue by jsuarez-chipiron** [bernhardfritz/piksel#2]
Simple project developed with piksel is working fine in Native (OSX) and Web in Chrome and Firefox but is not working for Safari 12.1. In the Safari console appers this errors:

WebGL: ERROR: unsupported shader version
compileShader
_glCompileShader — index.js:6549
wasm-stub
<?>.wasm-function[337]
<?>.wasm-function[339]
<?>.wasm-function[211]
<?>.wasm-function[113]
wasm-stub
_main
(anonymous function) — index.js:8233
callMain — index.js:8445
doRun — index.js:8503
(anonymous function) — index.js:8514
printErr — localhost:131

**Comment by bernhardfritz** [comment]
Hi @jsuarez-chipiron ! piksel uses WebGL2, which is currently not supported by Safari per default.
According to caniuse.com, Safari has an option to enable WebGL2 via the "Experimental Features" developer menu. However, due to the fact that Safari fails 77% of the WebGL2 conformance tests and has not seen any WebGL2 related development activity in over 3 years, my hopes are not that high that it will ever truly support it.
For a list of supported browsers check: https://caniuse.com/#feat=webgl2

**Comment by jsuarez-chipiron** [comment]
What I pitty!! I am developing a game with your piksel and I was hoping to run it into iOS devices :(
