### ISSUE TITLE
SignedDistance.h INFINITE e0040 error

### ISSUE THREAD

**Issue by SciK3** [bernhardfritz/piksel#5]
this may just me being dumb but VS keeps yelling at me that in SignedDistance.h, INFINITE isnt a proper identifier. Ive run out of ideas as to what the issue is, ive checked where INFINITE is defined (WinBase.h), ive tried defining INFINITE myself, etc etc.

Just a reminder as to what SignedDistance.h contains:

#pragma once

namespace msdfgen {

/// Represents a signed distance and alignment, which together can be compared to uniquely determine the closest edge segment.
class SignedDistance {

public:
    static const SignedDistance INFINITE;

    double distance;
    double dot;

    SignedDistance();
    SignedDistance(double dist, double d);

    friend bool operator<(SignedDistance a, SignedDistance b);
    friend bool operator>(SignedDistance a, SignedDistance b);
    friend bool operator<=(SignedDistance a, SignedDistance b);
    friend bool operator>=(SignedDistance a, SignedDistance b);

};

}

**Comment by bernhardfritz** [comment]
Hi @SciK3 
I think this problem might be caused by the compiler that ships with VS.
To compile piksel you need to use GCC: http://mingw-w64.org/doku.php/download/mingw-builds
I do not use VS myself, but I guess it should be possible configure VS to use mingw.
A fair bit of warning, though. I was never able to compile piksel natively on Windows, but then again I'm not that a profound C++ developer myself. If you have more luck, please share your results! For Windows the current recommended way to use piksel is to use WSL (Windows subsystem for Linux) and build for the web: https://bernhardfritz.github.io/piksel/#/gettingstarted/buildonwindows
FYI instead of raising an issue, we also have gitter which might be more suitable for questions: https://gitter.im/every-piksel-counts/Lobby
